/**
 * PalliCare Clinical Alert
 *
 * Schema for clinical alerts generated by the system for the clinician
 * dashboard. Three-tier system: critical, warning, informational.
 *
 * Generated from: schemas/clinical_alert.schema.json
 */

// ---------------------------------------------------------------------------
// Enums (as union types)
// ---------------------------------------------------------------------------

/** Three-tier alert severity */
export type AlertSeverity = 'critical' | 'warning' | 'informational';

/** Clinical alert type */
export type ClinicalAlertType =
  | 'pain_sustained_high'
  | 'pain_sudden_spike'
  | 'pain_trend_worsening'
  | 'medd_threshold'
  | 'opioid_side_effect_severe'
  | 'medication_non_adherence'
  | 'breakthrough_frequency_high'
  | 'mood_distress_sustained'
  | 'caregiver_distress'
  | 'esas_symptom_critical'
  | 'no_data_48h'
  | 'sleep_severely_disrupted'
  | 'functional_decline'
  | 'medication_interaction'
  | 'prn_overuse'
  | 'custom';

/** Alert lifecycle status */
export type AlertStatus =
  | 'active'
  | 'acknowledged'
  | 'in_progress'
  | 'resolved'
  | 'dismissed'
  | 'expired';

// ---------------------------------------------------------------------------
// Nested interfaces
// ---------------------------------------------------------------------------

/** The rule that triggered this alert */
export interface TriggerRule {
  /** e.g., "pain_intensity", "medd", "med_adherence" */
  metric?: string;
  /** e.g., ">= 9 for 2+ consecutive logs" */
  condition?: string;
  threshold?: number;
  /** Time window evaluated (hours) */
  window_hours?: number;
  /** The value that triggered the alert */
  actual_value?: number;
}

/** A recent pain score data point used as supporting evidence */
export interface PainScoreDataPoint {
  timestamp?: string;
  score?: number;
}

/** Data points that support this alert */
export interface SupportingData {
  recent_pain_scores?: PainScoreDataPoint[];
  current_medd?: number | null;
  medication_adherence_pct?: number | null;
  days_without_log?: number | null;
  related_log_ids?: string[];
}

// ---------------------------------------------------------------------------
// Root interface
// ---------------------------------------------------------------------------

/**
 * A clinical alert generated by the system for clinician dashboard.
 * Three-tier system: critical, warning, informational.
 */
export interface ClinicalAlert {
  id: string;
  patient_id: string;
  /** Three-tier alert severity */
  severity: AlertSeverity;
  /** Clinical alert type */
  type: ClinicalAlertType;
  /** The rule that triggered this alert */
  trigger_rule?: TriggerRule;
  /** Human-readable alert message for clinician */
  message: string;
  /** Suggested clinical action */
  recommendation?: string | null;
  /** Data points that support this alert */
  supporting_data?: SupportingData;
  /** Alert lifecycle status */
  status: AlertStatus;
  acknowledged_by?: string | null;
  acknowledged_at?: string | null;
  resolution_notes?: string | null;
  resolved_by?: string | null;
  resolved_at?: string | null;
  /** Escalation level: 0=not escalated, 1=nurse, 2=registrar, 3=consultant */
  escalation_level?: number;
  snoozed_until?: string | null;
  created_at?: string;
  updated_at?: string;
}
