// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'clinical_alert.freezed.dart';
part 'clinical_alert.g.dart';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/// Three-tier alert severity level for the clinician dashboard.
enum AlertSeverity {
  @JsonValue('critical')
  critical,
  @JsonValue('warning')
  warning,
  @JsonValue('informational')
  informational,
}

/// Type of clinical alert.
enum ClinicalAlertType {
  @JsonValue('pain_sustained_high')
  painSustainedHigh,
  @JsonValue('pain_sudden_spike')
  painSuddenSpike,
  @JsonValue('pain_trend_worsening')
  painTrendWorsening,
  @JsonValue('medd_threshold')
  meddThreshold,
  @JsonValue('opioid_side_effect_severe')
  opioidSideEffectSevere,
  @JsonValue('medication_non_adherence')
  medicationNonAdherence,
  @JsonValue('breakthrough_frequency_high')
  breakthroughFrequencyHigh,
  @JsonValue('mood_distress_sustained')
  moodDistressSustained,
  @JsonValue('caregiver_distress')
  caregiverDistress,
  @JsonValue('esas_symptom_critical')
  esasSymptomCritical,
  @JsonValue('no_data_48h')
  noData48h,
  @JsonValue('sleep_severely_disrupted')
  sleepSeverelyDisrupted,
  @JsonValue('functional_decline')
  functionalDecline,
  @JsonValue('medication_interaction')
  medicationInteraction,
  @JsonValue('prn_overuse')
  prnOveruse,
  @JsonValue('custom')
  custom,
}

/// Clinical alert lifecycle status.
enum ClinicalAlertStatus {
  @JsonValue('active')
  active,
  @JsonValue('acknowledged')
  acknowledged,
  @JsonValue('in_progress')
  inProgress,
  @JsonValue('resolved')
  resolved,
  @JsonValue('dismissed')
  dismissed,
  @JsonValue('expired')
  expired,
}

// ---------------------------------------------------------------------------
// Data Models
// ---------------------------------------------------------------------------

/// A clinical alert generated by the system for the clinician dashboard.
/// Uses a three-tier system: critical, warning, and informational.
@freezed
class ClinicalAlert with _$ClinicalAlert {
  const factory ClinicalAlert({
    /// Unique alert identifier.
    required String id,

    /// Reference to the patient.
    @JsonKey(name: 'patient_id') required String patientId,

    /// Three-tier alert severity.
    required AlertSeverity severity,

    /// Type of clinical alert.
    required ClinicalAlertType type,

    /// Human-readable alert message for the clinician (max 500 chars).
    required String message,

    /// Alert lifecycle status.
    required ClinicalAlertStatus status,

    /// The rule that triggered this alert.
    @JsonKey(name: 'trigger_rule') AlertTriggerRule? triggerRule,

    /// Suggested clinical action.
    String? recommendation,

    /// Data points supporting this alert.
    @JsonKey(name: 'supporting_data') AlertSupportingData? supportingData,

    /// Clinician who acknowledged the alert.
    @JsonKey(name: 'acknowledged_by') String? acknowledgedBy,

    /// When the alert was acknowledged.
    @JsonKey(name: 'acknowledged_at') DateTime? acknowledgedAt,

    /// Notes about the resolution.
    @JsonKey(name: 'resolution_notes') String? resolutionNotes,

    /// Clinician who resolved the alert.
    @JsonKey(name: 'resolved_by') String? resolvedBy,

    /// When the alert was resolved.
    @JsonKey(name: 'resolved_at') DateTime? resolvedAt,

    /// Escalation level (0=not escalated, 1=nurse, 2=registrar, 3=consultant).
    @JsonKey(name: 'escalation_level') @Default(0) int escalationLevel,

    /// Alert is snoozed until this timestamp.
    @JsonKey(name: 'snoozed_until') DateTime? snoozedUntil,

    /// Record creation timestamp.
    @JsonKey(name: 'created_at') DateTime? createdAt,

    /// Last updated timestamp.
    @JsonKey(name: 'updated_at') DateTime? updatedAt,
  }) = _ClinicalAlert;

  factory ClinicalAlert.fromJson(Map<String, dynamic> json) =>
      _$ClinicalAlertFromJson(json);
}

/// The rule definition that triggered a clinical alert.
@freezed
class AlertTriggerRule with _$AlertTriggerRule {
  const factory AlertTriggerRule({
    /// Metric being evaluated (e.g., 'pain_intensity', 'medd', 'med_adherence').
    String? metric,

    /// Condition expression (e.g., '>= 9 for 2+ consecutive logs').
    String? condition,

    /// Numeric threshold value.
    double? threshold,

    /// Time window evaluated in hours.
    @JsonKey(name: 'window_hours') int? windowHours,

    /// The actual value that triggered the alert.
    @JsonKey(name: 'actual_value') double? actualValue,
  }) = _AlertTriggerRule;

  factory AlertTriggerRule.fromJson(Map<String, dynamic> json) =>
      _$AlertTriggerRuleFromJson(json);
}

/// Supporting data points for a clinical alert.
@freezed
class AlertSupportingData with _$AlertSupportingData {
  const factory AlertSupportingData({
    /// Recent pain score observations.
    @JsonKey(name: 'recent_pain_scores') List<PainScoreEntry>? recentPainScores,

    /// Current total Morphine Equivalent Daily Dose.
    @JsonKey(name: 'current_medd') double? currentMedd,

    /// Medication adherence percentage (0-100).
    @JsonKey(name: 'medication_adherence_pct') double? medicationAdherencePct,

    /// Number of days without a symptom log entry.
    @JsonKey(name: 'days_without_log') int? daysWithoutLog,

    /// IDs of symptom log entries related to this alert.
    @JsonKey(name: 'related_log_ids') List<String>? relatedLogIds,
  }) = _AlertSupportingData;

  factory AlertSupportingData.fromJson(Map<String, dynamic> json) =>
      _$AlertSupportingDataFromJson(json);
}

/// A single pain score observation with timestamp.
@freezed
class PainScoreEntry with _$PainScoreEntry {
  const factory PainScoreEntry({
    /// When the pain score was recorded.
    DateTime? timestamp,

    /// Pain score value.
    int? score,
  }) = _PainScoreEntry;

  factory PainScoreEntry.fromJson(Map<String, dynamic> json) =>
      _$PainScoreEntryFromJson(json);
}
